CREATE TABLE SCHEDULE (
    ID INT PRIMARY KEY IDENTITY,
    EMP_ID INT NOT NULL,
    SHOP_ID INT NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
    CREATED_BY NVARCHAR(100),
    NOTES NVARCHAR(MAX)
);

CREATE TABLE TIME_OFF_REQUESTS (
    ID INT PRIMARY KEY IDENTITY,
    EMP_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    REASON NVARCHAR(255),
    STATUS NVARCHAR(50) DEFAULT 'Pending',
    SUBMITTED_AT DATETIME DEFAULT GETDATE()
);
